### ISSUE TITLE
Add .net standard 2.0 target to avoid unnecessary deps

### ISSUE THREAD

**Issue by RSuter** [Picturepark/Picturepark.SDK.DotNet#171]

**Comment by neotek** [comment]
@RSuter Agree. Do you have time to add the target and create a pull request?

**Comment by neotek** [comment]
@RSuter Thanks a lot. When installing the latest SDK in a .NET Core 2.2 app we still have a pretty large list of dependencies:

![image](https://user-images.githubusercontent.com/6042550/49689540-dec96300-fb22-11e8-9beb-57d5ca4232fc.png)

I guess due to Newtonsoft.Json 9.0.1 and Microsoft.Net.Http.Headers 1.0.0, as transitive dependencies restore on the lowest version. How do we address this?

**Comment by RSuter** [comment]
Yes, a little bit strange, but when looking at the actual dependencies it looks fine now: 

With .NET Standard 2.0: 

![image](https://user-images.githubusercontent.com/2603405/49861887-373b8180-fdfd-11e8-9bf4-3fa35440ebd0.png)

(.NET Core 1.1 still uses the "legacy" .NET Standard 1.3 target)

Without .NET Standard 2.0: 

![image](https://user-images.githubusercontent.com/2603405/49861943-5508e680-fdfd-11e8-9558-64c0dbaa949d.png)

**Comment by neotek** [comment]
Fixed. Updated Newtonsoft.Json to v 11 and removed Microsoft.Net.Http.Headers
